- name: Install virtualbox
  apt:
    name: virtualbox
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install ext pack
  apt:
    name: virtualbox-ext-pack
    state: present
    update_cache: true
    cache_valid_time: 3600
